### ISSUE TITLE
Please reconsider dependency on sonLib

### ISSUE THREAD

**Issue by dentearl** [benedictpaten/jobTree#22] opened 2014-12-14 00:02 UTC
Apart from the test data, why is jobTree dependent on sonLib? Free it from the shackles of unrelated projects!

**Comment by benedictpaten** [comment] 2015-04-09 00:55
Oops, this is a duplicate of an issue I just made. I agree, I'm going to remove it.

**Closed by benedictpaten** 2015-04-09 00:55 UTC
